#!/bin/bash

#****************************************************************************************************#
#                                   REMCHAIN-AUTOMATED-BOT (SETUP 1)                                 #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# INSTALLING REM PROTOCOL BINARIES                                                                   #
#----------------------------------------------------------------------------------------------------#

wget https://github.com/Remmeauth/remprotocol/releases/download/0.3.1/remprotocol_0.3.1_amd64.deb
sudo apt install ./remprotocol_0.3.1_amd64.deb

#----------------------------------------------------------------------------------------------------#
# RUNNING THE WALLET DAEMON                                                                          #
#----------------------------------------------------------------------------------------------------#

remvault &
sleep 2

printf "\n"
read -p 'Press [Enter] key to continue...'
printf "\n\n"

#----------------------------------------------------------------------------------------------------#
# CREATING THE REMCLI WALLET                                                                         #
#----------------------------------------------------------------------------------------------------#

remcli wallet create --file walletpass
walletpass=$(cat walletpass)
printf "\n\n"

#----------------------------------------------------------------------------------------------------#
# YOUR REMNODE WALLET PASSWORD                                                                       #
#----------------------------------------------------------------------------------------------------#

printf "[********************* TAKE NOTE OF YOUR WALLET PASSWORD *********************]\n\n"

cat ./walletpass
printf "\n"
echo " "
echo " "
read -p 'Press [Enter] key to continue...'
printf "\n\n"

#----------------------------------------------------------------------------------------------------#
# INPUT YOUR GUARDIAN PRIVATE KEY                                                                    #
#----------------------------------------------------------------------------------------------------#

printf "[********************* ENTER YOUR GUARDIAN PRIVATE KEY ***********************]\n\n"

while [ : ]
do
          read -p "ENTER YOUR GUARDIAN PRIVATE KEY: " guardianprivatekey

	  if [[ ! "$guardianprivatekey" = "${guardianprivatekey%[[:space:]]*}" ]]; then
	        printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SPACES.\n\n"
                continue

        elif [[ ${#guardianprivatekey} -ne 51 ]]; then
                printf "\nERROR: PRIVATE KEY SHOULD ONLY BE 51 CHARACTERS LONG.\n\n"
                continue

       	elif [[ "$guardianprivatekey" =~ ['!@#$%^&*()_+,.£'] ]]; then
	        printf "\nERROR: PRIVATE KEY SHOULDN'T CONTAIN ANY SYMBOLS.\n\n"
		continue

	else
                break
          fi
done

#----------------------------------------------------------------------------------------------------#
# IMPORT YOUR GUARDIAN KEY INTO THE WALLET                                                           #
#----------------------------------------------------------------------------------------------------#

printf "\n\n"

remcli wallet lock > /dev/null 2>&1
remcli wallet unlock --password=$walletpass > /dev/null 2>&1
remcli wallet import --private-key=$guardianprivatekey
rm mainnet-autobot-setup1

printf "\n\n"
